#!/usr/bin/env bash
# Interactive setup script for new book project

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}📚 Ebook Generation Engine - Project Setup${NC}"
echo ""

# Function to prompt for input
prompt() {
    local prompt_text="$1"
    local default_value="${2:-}"
    local var_name="$3"
    
    if [ -n "$default_value" ]; then
        read -p "$prompt_text [$default_value]: " input
        eval "$var_name=\"\${input:-$default_value}\""
    else
        read -p "$prompt_text: " input
        eval "$var_name=\"$input\""
    fi
}

# Function to prompt for yes/no
prompt_yesno() {
    local prompt_text="$1"
    local default_value="${2:-y}"
    local var_name="$3"
    
    while true; do
        read -p "$prompt_text [y/n] [$default_value]: " input
        input="${input:-$default_value}"
        case $input in
            [Yy]* ) eval "$var_name=\"yes\""; break;;
            [Nn]* ) eval "$var_name=\"no\""; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

# Collect book information
echo -e "${GREEN}Book Information:${NC}"
prompt "Book title" "" "BOOK_TITLE"
prompt "Book subtitle (optional)" "" "BOOK_SUBTITLE"
prompt "Author name (optional)" "" "BOOK_AUTHOR"
prompt "Publisher name" "Your Publisher" "BOOK_PUBLISHER"
prompt "Publication date" "2025" "BOOK_DATE"
prompt "Language code" "en-US" "BOOK_LANGUAGE"

echo ""
echo -e "${GREEN}Book Structure:${NC}"
prompt "Number of chapters" "8" "NUM_CHAPTERS"
prompt_yesno "Do you have a conclusion chapter?" "yes" "HAS_CONCLUSION"

echo ""
echo -e "${GREEN}Appendices (optional):${NC}"
echo "Enter appendix filenames (one per line, empty line to finish):"
APPENDICES=()
while IFS= read -r line; do
    [ -z "$line" ] && break
    APPENDICES+=("$line")
done

echo ""
prompt "Cover image path (optional)" "book_content/cover_epub.png" "COVER_IMAGE"

# Create folder structure
echo ""
echo -e "${BLUE}Creating folder structure...${NC}"
mkdir -p "$PROJECT_ROOT/book_content"/{front_matter,chapters,back_matter}
mkdir -p "$PROJECT_ROOT/output"

# Create placeholder markdown files
echo -e "${BLUE}Creating placeholder files...${NC}"

# Front matter
cat > "$PROJECT_ROOT/book_content/front_matter/title_page.md" << EOF
# $BOOK_TITLE
## $BOOK_SUBTITLE

**$BOOK_PUBLISHER**  
*$BOOK_DATE*
EOF

cat > "$PROJECT_ROOT/book_content/front_matter/copyright_page.md" << EOF
# Copyright

Copyright © $BOOK_DATE by $BOOK_PUBLISHER

All rights reserved.

**Publisher:** $BOOK_PUBLISHER
EOF

cat > "$PROJECT_ROOT/book_content/front_matter/dedication.md" << EOF
# Dedication

[Your dedication here]
EOF

cat > "$PROJECT_ROOT/book_content/front_matter/table_of_contents.md" << EOF
# Table of Contents

[Table of contents will be generated automatically]
EOF

cat > "$PROJECT_ROOT/book_content/front_matter/preface.md" << EOF
# Preface

[Your preface here]
EOF

# Chapters
for i in $(seq 1 "$NUM_CHAPTERS"); do
    cat > "$PROJECT_ROOT/book_content/chapters/chapter_${i}.md" << EOF
# Chapter $i

[Chapter $i content here]
EOF
done

# Conclusion
if [ "$HAS_CONCLUSION" = "yes" ]; then
    cat > "$PROJECT_ROOT/book_content/chapters/conclusion.md" << EOF
# Conclusion

[Your conclusion here]
EOF
fi

# Back matter
cat > "$PROJECT_ROOT/book_content/back_matter/acknowledgments.md" << EOF
# Acknowledgments

[Your acknowledgments here]
EOF

# Appendices
for appendix in "${APPENDICES[@]}"; do
    cat > "$PROJECT_ROOT/book_content/back_matter/$appendix" << EOF
# ${appendix%.md}

[Appendix content here]
EOF
done

# Generate config.yaml
echo -e "${BLUE}Generating config.yaml...${NC}"

# Build appendices YAML
APPENDICES_YAML=""
if [ ${#APPENDICES[@]} -gt 0 ]; then
    APPENDICES_YAML="appendices:"
    for appendix in "${APPENDICES[@]}"; do
        APPENDICES_YAML="$APPENDICES_YAML"$'\n'"    - $appendix"
    done
else
    APPENDICES_YAML="appendices: []"
fi

cat > "$PROJECT_ROOT/config.yaml" << EOF
# Book Metadata Configuration
# Generated by setup_project.sh

book:
  title: "$BOOK_TITLE"
  subtitle: "$BOOK_SUBTITLE"
  author: "$BOOK_AUTHOR"
  publisher: "$BOOK_PUBLISHER"
  date: "$BOOK_DATE"
  language: "$BOOK_LANGUAGE"
  description: "A comprehensive guide..."
  rights: "Copyright © $BOOK_DATE by $BOOK_PUBLISHER. All rights reserved."

structure:
  chapters: $NUM_CHAPTERS
  has_conclusion: $HAS_CONCLUSION
  $APPENDICES_YAML
  cover_image: "$COVER_IMAGE"

output:
  epub_filename: ""
  pdf_filename: ""
  word_filename: ""
  output_dir: "output"

styles:
  epub_css: "styles/ebook_styles.css"
  print_css: "styles/print_styles.css"
  word_template: "styles/word_template.docx"
EOF

echo ""
echo -e "${GREEN}✅ Project setup complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Edit your content files in book_content/"
echo "2. Review and edit config.yaml if needed"
echo "3. Run: ./scripts/generate_all.sh"
echo ""
